//! The key-name table: the single source of truth mapping friendly key names
//! (lowercase evdev names without the `KEY_` prefix: `a`, `f5`, `leftctrl`,
//! `kp1`, ...) to evdev codes, uinput events, and back.
//! See DESIGN.md §"Key naming".
//!
//! The table is generated by the [`keys!`] macro so that a name, its evdev
//! constant and its `uinput-tokio` event variant can never drift apart: adding
//! a key means adding exactly one row.

use uinput_tokio::event::keyboard::{
    Key as UKey, KeyPad as UKeyPad, Keyboard as UKeyboard, Misc as UMisc,
};

/// A raw evdev key code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct KeyCode(pub u16);

impl KeyCode {
    /// The raw evdev code carried by this key.
    pub const fn code(self) -> u16 {
        self.0
    }
}

impl std::fmt::Display for KeyCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match name(*self) {
            Some(name) => f.write_str(name),
            None => write!(f, "<unnamed key {}>", self.0),
        }
    }
}

/// Resolves the `uinput-tokio` event for one table row.
///
/// `uinput-tokio` splits the keyboard key space across several enums, so the
/// table names the family (`key`, `pad`, `misc`) alongside the variant. A row
/// whose key has no variant in the crate at all is written `none`; such keys
/// fall back to raw `EV_KEY` writes in [`crate::output::uinput`], and cannot be
/// registered as a device capability.
macro_rules! uinput_event {
    (key $variant:ident) => {
        Some(UKeyboard::Key(UKey::$variant))
    };
    (pad $variant:ident) => {
        Some(UKeyboard::KeyPad(UKeyPad::$variant))
    };
    (misc $variant:ident) => {
        Some(UKeyboard::Misc(UMisc::$variant))
    };
    (none) => {
        None
    };
}

/// Generates the whole key table from a list of
/// `"name" => EVDEV_CONSTANT / <family> <UinputVariant>` rows.
macro_rules! keys {
    ($($name:literal => $evdev:ident / $family:ident $($variant:ident)?),* $(,)?) => {
        /// Every friendly key name, in table order.
        const NAMES: &[&str] = &[$($name),*];

        /// Every key code in the table, in table order.
        const CODES: &[KeyCode] = &[$(KeyCode(evdev::KeyCode::$evdev.0)),*];

        /// Looks up a key by its friendly name (`"leftctrl"`, `"f5"`, `"kp1"`).
        ///
        /// Returns `None` for names which are not in the table; callers should
        /// pair that with [`suggest`] to produce a "did you mean" hint.
        pub fn from_name(name: &str) -> Option<KeyCode> {
            match name {
                $($name => Some(KeyCode(evdev::KeyCode::$evdev.0)),)*
                _ => None,
            }
        }

        /// The friendly name for a key code, if it is one we know about.
        pub fn name(code: KeyCode) -> Option<&'static str> {
            match evdev::KeyCode(code.0) {
                $(evdev::KeyCode::$evdev => Some($name),)*
                _ => None,
            }
        }

        /// The `uinput-tokio` event for a key, where the crate models it.
        ///
        /// `None` means `uinput-tokio` has no variant for this code; the device
        /// wrapper falls back to writing the raw `EV_KEY` code instead.
        pub fn to_uinput(code: KeyCode) -> Option<UKeyboard> {
            match evdev::KeyCode(code.0) {
                $(evdev::KeyCode::$evdev => uinput_event!($family $($variant)?),)*
                _ => None,
            }
        }
    };
}

keys! {
    // Letters.
    "a" => KEY_A / key A,
    "b" => KEY_B / key B,
    "c" => KEY_C / key C,
    "d" => KEY_D / key D,
    "e" => KEY_E / key E,
    "f" => KEY_F / key F,
    "g" => KEY_G / key G,
    "h" => KEY_H / key H,
    "i" => KEY_I / key I,
    "j" => KEY_J / key J,
    "k" => KEY_K / key K,
    "l" => KEY_L / key L,
    "m" => KEY_M / key M,
    "n" => KEY_N / key N,
    "o" => KEY_O / key O,
    "p" => KEY_P / key P,
    "q" => KEY_Q / key Q,
    "r" => KEY_R / key R,
    "s" => KEY_S / key S,
    "t" => KEY_T / key T,
    "u" => KEY_U / key U,
    "v" => KEY_V / key V,
    "w" => KEY_W / key W,
    "x" => KEY_X / key X,
    "y" => KEY_Y / key Y,
    "z" => KEY_Z / key Z,

    // Digit row.
    "0" => KEY_0 / key _0,
    "1" => KEY_1 / key _1,
    "2" => KEY_2 / key _2,
    "3" => KEY_3 / key _3,
    "4" => KEY_4 / key _4,
    "5" => KEY_5 / key _5,
    "6" => KEY_6 / key _6,
    "7" => KEY_7 / key _7,
    "8" => KEY_8 / key _8,
    "9" => KEY_9 / key _9,

    // Function keys.
    "f1" => KEY_F1 / key F1,
    "f2" => KEY_F2 / key F2,
    "f3" => KEY_F3 / key F3,
    "f4" => KEY_F4 / key F4,
    "f5" => KEY_F5 / key F5,
    "f6" => KEY_F6 / key F6,
    "f7" => KEY_F7 / key F7,
    "f8" => KEY_F8 / key F8,
    "f9" => KEY_F9 / key F9,
    "f10" => KEY_F10 / key F10,
    "f11" => KEY_F11 / key F11,
    "f12" => KEY_F12 / key F12,
    "f13" => KEY_F13 / key F13,
    "f14" => KEY_F14 / key F14,
    "f15" => KEY_F15 / key F15,
    "f16" => KEY_F16 / key F16,
    "f17" => KEY_F17 / key F17,
    "f18" => KEY_F18 / key F18,
    "f19" => KEY_F19 / key F19,
    "f20" => KEY_F20 / key F20,
    "f21" => KEY_F21 / key F21,
    "f22" => KEY_F22 / key F22,
    "f23" => KEY_F23 / key F23,
    "f24" => KEY_F24 / key F24,

    // Typing keys and punctuation.
    "space" => KEY_SPACE / key Space,
    "enter" => KEY_ENTER / key Enter,
    "esc" => KEY_ESC / key Esc,
    "tab" => KEY_TAB / key Tab,
    "backspace" => KEY_BACKSPACE / key BackSpace,
    "minus" => KEY_MINUS / key Minus,
    "equal" => KEY_EQUAL / key Equal,
    "leftbrace" => KEY_LEFTBRACE / key LeftBrace,
    "rightbrace" => KEY_RIGHTBRACE / key RightBrace,
    "semicolon" => KEY_SEMICOLON / key SemiColon,
    "apostrophe" => KEY_APOSTROPHE / key Apostrophe,
    "grave" => KEY_GRAVE / key Grave,
    "backslash" => KEY_BACKSLASH / key BackSlash,
    "comma" => KEY_COMMA / key Comma,
    "dot" => KEY_DOT / key Dot,
    "slash" => KEY_SLASH / key Slash,
    "capslock" => KEY_CAPSLOCK / key CapsLock,

    // Modifiers.
    "leftctrl" => KEY_LEFTCTRL / key LeftControl,
    "rightctrl" => KEY_RIGHTCTRL / key RightControl,
    "leftshift" => KEY_LEFTSHIFT / key LeftShift,
    "rightshift" => KEY_RIGHTSHIFT / key RightShift,
    "leftalt" => KEY_LEFTALT / key LeftAlt,
    "rightalt" => KEY_RIGHTALT / key RightAlt,
    "leftmeta" => KEY_LEFTMETA / key LeftMeta,
    "rightmeta" => KEY_RIGHTMETA / key RightMeta,

    // Arrows.
    "up" => KEY_UP / key Up,
    "down" => KEY_DOWN / key Down,
    "left" => KEY_LEFT / key Left,
    "right" => KEY_RIGHT / key Right,

    // Navigation cluster.
    "insert" => KEY_INSERT / key Insert,
    "delete" => KEY_DELETE / key Delete,
    "home" => KEY_HOME / key Home,
    "end" => KEY_END / key End,
    "pageup" => KEY_PAGEUP / key PageUp,
    "pagedown" => KEY_PAGEDOWN / key PageDown,

    // System keys.
    "sysrq" => KEY_SYSRQ / key SysRq,
    "scrolllock" => KEY_SCROLLLOCK / key ScrollLock,
    "pause" => KEY_PAUSE / misc Pause,
    "numlock" => KEY_NUMLOCK / key NumLock,

    // Keypad.
    "kp0" => KEY_KP0 / pad _0,
    "kp1" => KEY_KP1 / pad _1,
    "kp2" => KEY_KP2 / pad _2,
    "kp3" => KEY_KP3 / pad _3,
    "kp4" => KEY_KP4 / pad _4,
    "kp5" => KEY_KP5 / pad _5,
    "kp6" => KEY_KP6 / pad _6,
    "kp7" => KEY_KP7 / pad _7,
    "kp8" => KEY_KP8 / pad _8,
    "kp9" => KEY_KP9 / pad _9,
    "kpslash" => KEY_KPSLASH / pad Slash,
    "kpasterisk" => KEY_KPASTERISK / pad Asterisk,
    "kpminus" => KEY_KPMINUS / pad Minus,
    "kpplus" => KEY_KPPLUS / pad Plus,
    "kpenter" => KEY_KPENTER / pad Enter,
    "kpdot" => KEY_KPDOT / pad Dot,

    // Media keys.
    "mute" => KEY_MUTE / misc Mute,
    "volumeup" => KEY_VOLUMEUP / misc VolumeUp,
    "volumedown" => KEY_VOLUMEDOWN / misc VolumeDown,
    "playpause" => KEY_PLAYPAUSE / misc PlayPause,
    "nextsong" => KEY_NEXTSONG / misc NextSong,
    "previoussong" => KEY_PREVIOUSSONG / misc PreviousSong,
}

/// The evdev key code for a key, used when matching hotkey events read from
/// `/dev/input/event*`.
pub fn to_evdev(code: KeyCode) -> evdev::KeyCode {
    evdev::KeyCode(code.0)
}

/// Every friendly key name we accept, in table order.
///
/// Used by the key reference documentation and by [`suggest`].
pub fn all_names() -> &'static [&'static str] {
    NAMES
}

/// Every key code in the table, in table order.
///
/// The uinput device registers all of these as capabilities so that it looks
/// like a real keyboard to SDL and games (DESIGN.md §"`run` assembly").
pub fn all_codes() -> &'static [KeyCode] {
    CODES
}

/// The largest edit distance we will still call a typo.
const MAX_SUGGESTION_DISTANCE: usize = 2;

/// A `strsim`-ranked "did you mean ...?" suggestion for an unknown key name.
///
/// Candidates within [`MAX_SUGGESTION_DISTANCE`] edits are ranked by distance,
/// then by whether they share the misspelling's first letter (typos rarely
/// change it), then by how close their length is, and finally alphabetically so
/// the result is deterministic.
///
/// A candidate must also differ by fewer edits than the shorter of the two
/// names is long, which is what stops short nonsense from matching short keys —
/// `"zzz"` is two edits from `"z"`, but nobody meant `"z"`.
pub fn suggest(name: &str) -> Option<&'static str> {
    let name = name.trim().to_ascii_lowercase();
    if name.is_empty() {
        return None;
    }

    let first = name.chars().next();

    all_names()
        .iter()
        .copied()
        .filter_map(|candidate| {
            let distance = strsim::levenshtein(&name, candidate);
            let plausible =
                distance <= MAX_SUGGESTION_DISTANCE && distance < name.len().min(candidate.len());
            plausible.then_some((distance, candidate))
        })
        .min_by_key(|(distance, candidate)| {
            (
                *distance,
                // `false` sorts first, so a shared first letter wins ties.
                candidate.chars().next() != first,
                candidate.len().abs_diff(name.len()),
                *candidate,
            )
        })
        .map(|(_, candidate)| candidate)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    #[test]
    fn every_name_round_trips() {
        for &name in all_names() {
            let code = from_name(name).unwrap_or_else(|| panic!("'{name}' is not resolvable"));
            let back = super::name(code).unwrap_or_else(|| panic!("{code:?} has no name"));
            assert_eq!(back, name, "'{name}' did not round-trip");
            assert_eq!(
                from_name(back),
                Some(code),
                "'{name}' did not round-trip back to the same code"
            );
        }
    }

    #[test]
    fn names_and_codes_are_unique_and_aligned() {
        assert_eq!(all_names().len(), all_codes().len());

        let names: std::collections::HashSet<_> = all_names().iter().collect();
        assert_eq!(
            names.len(),
            all_names().len(),
            "duplicate key name in table"
        );

        let codes: std::collections::HashSet<_> = all_codes().iter().collect();
        assert_eq!(
            codes.len(),
            all_codes().len(),
            "duplicate key code in table"
        );

        for (&name, &code) in all_names().iter().zip(all_codes()) {
            assert_eq!(from_name(name), Some(code), "'{name}' is misaligned");
        }
    }

    #[test]
    fn every_name_has_a_uinput_event() {
        // DESIGN.md §Risks 7: verify uinput-tokio covers the whole table. Any
        // key which is not covered can still be written as a raw EV_KEY code,
        // but cannot be registered as a device capability, so a gap here is
        // worth knowing about.
        let missing: Vec<_> = all_names()
            .iter()
            .filter(|name| to_uinput(from_name(name).unwrap()).is_none())
            .collect();
        assert!(missing.is_empty(), "no uinput event for: {missing:?}");
    }

    #[rstest]
    #[case("a", evdev::KeyCode::KEY_A)]
    #[case("z", evdev::KeyCode::KEY_Z)]
    #[case("0", evdev::KeyCode::KEY_0)]
    #[case("9", evdev::KeyCode::KEY_9)]
    #[case("f5", evdev::KeyCode::KEY_F5)]
    #[case("f24", evdev::KeyCode::KEY_F24)]
    #[case("leftctrl", evdev::KeyCode::KEY_LEFTCTRL)]
    #[case("rightmeta", evdev::KeyCode::KEY_RIGHTMETA)]
    #[case("space", evdev::KeyCode::KEY_SPACE)]
    #[case("kp1", evdev::KeyCode::KEY_KP1)]
    #[case("kpasterisk", evdev::KeyCode::KEY_KPASTERISK)]
    #[case("pause", evdev::KeyCode::KEY_PAUSE)]
    #[case("playpause", evdev::KeyCode::KEY_PLAYPAUSE)]
    #[case("previoussong", evdev::KeyCode::KEY_PREVIOUSSONG)]
    fn to_evdev_agrees_with_evdev(#[case] name: &str, #[case] expected: evdev::KeyCode) {
        let code = from_name(name).expect("known key");
        assert_eq!(to_evdev(code), expected);
        assert_eq!(code.code(), expected.0);
    }

    #[test]
    fn unknown_names_do_not_resolve() {
        assert_eq!(from_name("leftcontrol"), None);
        assert_eq!(from_name("LEFTCTRL"), None);
        assert_eq!(from_name(""), None);
        assert_eq!(name(KeyCode(60000)), None);
    }

    #[rstest]
    #[case("leftctl", "leftctrl")]
    #[case("lefctrl", "leftctrl")]
    #[case("leftctrll", "leftctrl")]
    #[case("LeftCtrl", "leftctrl")]
    #[case("esk", "esc")]
    #[case("spce", "space")]
    #[case("entre", "enter")]
    #[case("bakspace", "backspace")]
    #[case("pgup", "pageup")]
    #[case("kpplu", "kpplus")]
    #[case("volumup", "volumeup")]
    fn suggest_finds_realistic_typos(#[case] typo: &str, #[case] expected: &str) {
        assert_eq!(suggest(typo), Some(expected), "suggestion for '{typo}'");
    }

    #[rstest]
    #[case("zzz")]
    #[case("zz")]
    #[case("")]
    #[case("supercalifragilistic")]
    #[case("mouse_wheel_up")]
    fn suggest_gives_up_on_nonsense(#[case] input: &str) {
        assert_eq!(suggest(input), None, "unexpected suggestion for '{input}'");
    }

    #[test]
    fn display_names_known_keys() {
        assert_eq!(from_name("leftctrl").unwrap().to_string(), "leftctrl");
        assert_eq!(KeyCode(60000).to_string(), "<unnamed key 60000>");
    }
}
