//! The key-name table: the single source of truth mapping friendly key names
//! (lowercase evdev names without the `KEY_` prefix: `a`, `f5`, `leftctrl`,
//! `kp1`, ...) to evdev codes, uinput events, Windows scancodes, and back.
//! See DESIGN.md §"Key naming".
//!
//! The table is generated by the [`keys!`] macro so that a name, its key code,
//! its `uinput-tokio` event variant and its Windows encoding can never drift
//! apart: adding a key means adding exactly one row.
//!
//! **Key codes are the crate's own currency.** The identifier in each row —
//! `KEY_A`, `KEY_LEFTCTRL` — names the evdev constant the literal beside it is
//! taken from, but the literal is what the table actually carries, because the
//! `evdev` crate is a Linux-only dependency and this table has to compile
//! everywhere. A `#[cfg(target_os = "linux")]` test asserts every literal
//! against its `evdev::KeyCode::KEY_*` constant, which is the compile-time
//! guarantee the constants used to give.
//!
//! **The Windows column** encodes each key the way `SendInput` wants it (see
//! [`WinKey`]). Three facts shape it:
//!
//! 1. evdev key codes `1..=88` are numerically identical to AT set-1
//!    scancodes (`KEY_ESC` = 1 = `0x01`, `KEY_A` = 30 = `0x1E`, `KEY_SPACE` =
//!    57 = `0x39`, `KEY_F12` = 88 = `0x58`), so those rows repeat their own
//!    code in hexadecimal.
//! 2. Everything above that is an `E0`-prefixed ("extended") scancode written
//!    `win_ext(...)`, or — for `F13`..`F24` — the non-extended `0x64`..`0x6F`
//!    block.
//! 3. `pause` cannot be expressed as a scancode at all: the keyboard sends it
//!    as the `E1 1D 45` sequence, which `SendInput`'s single-scancode field
//!    cannot carry. It is the one row injected by virtual key instead
//!    (`win_vk(VK_PAUSE)`).

#[cfg(target_os = "linux")]
use uinput_tokio::event::keyboard::{
    Key as UKey, KeyPad as UKeyPad, Keyboard as UKeyboard, Misc as UMisc,
};

/// A raw evdev key code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct KeyCode(pub u16);

impl KeyCode {
    /// The raw evdev code carried by this key.
    pub const fn code(self) -> u16 {
        self.0
    }
}

impl std::fmt::Display for KeyCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match name(*self) {
            Some(name) => f.write_str(name),
            None => write!(f, "<unnamed key {}>", self.0),
        }
    }
}

/// How a key has to be handed to the Windows `SendInput` API.
///
/// Scancodes are preferred over virtual keys throughout: a game reading raw
/// input (which is most of them) sees a scancode where it would ignore a
/// synthesized virtual key, and a scancode is layout-independent — `w` is the
/// key above `s` on an AZERTY keyboard too, which is what a movement macro
/// means.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WinKey {
    /// A plain AT set-1 scancode: `KEYEVENTF_SCANCODE` with `wScan` set to it.
    Scan(u16),
    /// An `E0`-prefixed scancode — the second byte of the pair — which
    /// additionally needs `KEYEVENTF_EXTENDEDKEY`.
    ScanExt(u16),
    /// A virtual-key code, for the one key (`pause`) whose scancode is a
    /// multi-byte `E1` sequence `SendInput` cannot express.
    VirtualKey(u16),
}

/// Resolves the `uinput-tokio` event for one table row.
///
/// `uinput-tokio` splits the keyboard key space across several enums, so the
/// table names the family (`key`, `pad`, `misc`) alongside the variant. A row
/// whose key has no variant in the crate at all is written `none`; such keys
/// fall back to raw `EV_KEY` writes in [`crate::output::uinput`], and cannot be
/// registered as a device capability.
#[cfg(target_os = "linux")]
macro_rules! uinput_event {
    (key $variant:ident) => {
        Some(UKeyboard::Key(UKey::$variant))
    };
    (pad $variant:ident) => {
        Some(UKeyboard::KeyPad(UKeyPad::$variant))
    };
    (misc $variant:ident) => {
        Some(UKeyboard::Misc(UMisc::$variant))
    };
    (none) => {
        None
    };
}

/// Resolves the [`WinKey`] for one table row's third column.
macro_rules! win_key {
    (win, $scan:literal) => {
        WinKey::Scan($scan)
    };
    (win_ext, $scan:literal) => {
        WinKey::ScanExt($scan)
    };
    (win_vk, $vk:literal) => {
        WinKey::VirtualKey($vk)
    };
}

/// Generates the whole key table from a list of
/// `"name" => EVDEV_CONSTANT = <code> / <family> <UinputVariant> / <windows>`
/// rows.
macro_rules! keys {
    ($($name:literal => $evdev:ident = $code:literal
        / $family:ident $($variant:ident)?
        / $win:ident($scan:literal)),* $(,)?) => {
        /// Every friendly key name, in table order.
        const NAMES: &[&str] = &[$($name),*];

        /// Every key code in the table, in table order.
        const CODES: &[KeyCode] = &[$(KeyCode($code)),*];

        /// Every row's name, code and `evdev` constant, for the test which
        /// pins the literals above against the kernel's own numbering.
        #[cfg(all(test, target_os = "linux"))]
        const EVDEV_ROWS: &[(&str, u16, evdev::KeyCode)] =
            &[$(($name, $code, evdev::KeyCode::$evdev)),*];

        /// Looks up a key by its friendly name (`"leftctrl"`, `"f5"`, `"kp1"`).
        ///
        /// Returns `None` for names which are not in the table; callers should
        /// pair that with [`suggest`] to produce a "did you mean" hint.
        pub fn from_name(name: &str) -> Option<KeyCode> {
            match name {
                $($name => Some(KeyCode($code)),)*
                _ => None,
            }
        }

        /// The friendly name for a key code, if it is one we know about.
        pub fn name(code: KeyCode) -> Option<&'static str> {
            match code.0 {
                $($code => Some($name),)*
                _ => None,
            }
        }

        /// The `uinput-tokio` event for a key, where the crate models it.
        ///
        /// `None` means `uinput-tokio` has no variant for this code; the device
        /// wrapper falls back to writing the raw `EV_KEY` code instead.
        #[cfg(target_os = "linux")]
        pub fn to_uinput(code: KeyCode) -> Option<UKeyboard> {
            match code.0 {
                $($code => uinput_event!($family $($variant)?),)*
                _ => None,
            }
        }

        /// How to hand a key to Windows' `SendInput`, for keys in the table.
        ///
        /// Kept compiled on every platform — it is pure data, and a table only
        /// Windows could see would be a table only Windows could test.
        pub fn to_windows(code: KeyCode) -> Option<WinKey> {
            match code.0 {
                $($code => Some(win_key!($win, $scan)),)*
                _ => None,
            }
        }
    };
}

keys! {
    // Letters.
    "a" => KEY_A = 30 / key A / win(0x1E),
    "b" => KEY_B = 48 / key B / win(0x30),
    "c" => KEY_C = 46 / key C / win(0x2E),
    "d" => KEY_D = 32 / key D / win(0x20),
    "e" => KEY_E = 18 / key E / win(0x12),
    "f" => KEY_F = 33 / key F / win(0x21),
    "g" => KEY_G = 34 / key G / win(0x22),
    "h" => KEY_H = 35 / key H / win(0x23),
    "i" => KEY_I = 23 / key I / win(0x17),
    "j" => KEY_J = 36 / key J / win(0x24),
    "k" => KEY_K = 37 / key K / win(0x25),
    "l" => KEY_L = 38 / key L / win(0x26),
    "m" => KEY_M = 50 / key M / win(0x32),
    "n" => KEY_N = 49 / key N / win(0x31),
    "o" => KEY_O = 24 / key O / win(0x18),
    "p" => KEY_P = 25 / key P / win(0x19),
    "q" => KEY_Q = 16 / key Q / win(0x10),
    "r" => KEY_R = 19 / key R / win(0x13),
    "s" => KEY_S = 31 / key S / win(0x1F),
    "t" => KEY_T = 20 / key T / win(0x14),
    "u" => KEY_U = 22 / key U / win(0x16),
    "v" => KEY_V = 47 / key V / win(0x2F),
    "w" => KEY_W = 17 / key W / win(0x11),
    "x" => KEY_X = 45 / key X / win(0x2D),
    "y" => KEY_Y = 21 / key Y / win(0x15),
    "z" => KEY_Z = 44 / key Z / win(0x2C),

    // Digit row.
    "0" => KEY_0 = 11 / key _0 / win(0x0B),
    "1" => KEY_1 = 2 / key _1 / win(0x02),
    "2" => KEY_2 = 3 / key _2 / win(0x03),
    "3" => KEY_3 = 4 / key _3 / win(0x04),
    "4" => KEY_4 = 5 / key _4 / win(0x05),
    "5" => KEY_5 = 6 / key _5 / win(0x06),
    "6" => KEY_6 = 7 / key _6 / win(0x07),
    "7" => KEY_7 = 8 / key _7 / win(0x08),
    "8" => KEY_8 = 9 / key _8 / win(0x09),
    "9" => KEY_9 = 10 / key _9 / win(0x0A),

    // Function keys.
    "f1" => KEY_F1 = 59 / key F1 / win(0x3B),
    "f2" => KEY_F2 = 60 / key F2 / win(0x3C),
    "f3" => KEY_F3 = 61 / key F3 / win(0x3D),
    "f4" => KEY_F4 = 62 / key F4 / win(0x3E),
    "f5" => KEY_F5 = 63 / key F5 / win(0x3F),
    "f6" => KEY_F6 = 64 / key F6 / win(0x40),
    "f7" => KEY_F7 = 65 / key F7 / win(0x41),
    "f8" => KEY_F8 = 66 / key F8 / win(0x42),
    "f9" => KEY_F9 = 67 / key F9 / win(0x43),
    "f10" => KEY_F10 = 68 / key F10 / win(0x44),
    "f11" => KEY_F11 = 87 / key F11 / win(0x57),
    "f12" => KEY_F12 = 88 / key F12 / win(0x58),
    "f13" => KEY_F13 = 183 / key F13 / win(0x64),
    "f14" => KEY_F14 = 184 / key F14 / win(0x65),
    "f15" => KEY_F15 = 185 / key F15 / win(0x66),
    "f16" => KEY_F16 = 186 / key F16 / win(0x67),
    "f17" => KEY_F17 = 187 / key F17 / win(0x68),
    "f18" => KEY_F18 = 188 / key F18 / win(0x69),
    "f19" => KEY_F19 = 189 / key F19 / win(0x6A),
    "f20" => KEY_F20 = 190 / key F20 / win(0x6B),
    "f21" => KEY_F21 = 191 / key F21 / win(0x6C),
    "f22" => KEY_F22 = 192 / key F22 / win(0x6D),
    "f23" => KEY_F23 = 193 / key F23 / win(0x6E),
    "f24" => KEY_F24 = 194 / key F24 / win(0x6F),

    // Typing keys and punctuation.
    "space" => KEY_SPACE = 57 / key Space / win(0x39),
    "enter" => KEY_ENTER = 28 / key Enter / win(0x1C),
    "esc" => KEY_ESC = 1 / key Esc / win(0x01),
    "tab" => KEY_TAB = 15 / key Tab / win(0x0F),
    "backspace" => KEY_BACKSPACE = 14 / key BackSpace / win(0x0E),
    "minus" => KEY_MINUS = 12 / key Minus / win(0x0C),
    "equal" => KEY_EQUAL = 13 / key Equal / win(0x0D),
    "leftbrace" => KEY_LEFTBRACE = 26 / key LeftBrace / win(0x1A),
    "rightbrace" => KEY_RIGHTBRACE = 27 / key RightBrace / win(0x1B),
    "semicolon" => KEY_SEMICOLON = 39 / key SemiColon / win(0x27),
    "apostrophe" => KEY_APOSTROPHE = 40 / key Apostrophe / win(0x28),
    "grave" => KEY_GRAVE = 41 / key Grave / win(0x29),
    "backslash" => KEY_BACKSLASH = 43 / key BackSlash / win(0x2B),
    "comma" => KEY_COMMA = 51 / key Comma / win(0x33),
    "dot" => KEY_DOT = 52 / key Dot / win(0x34),
    "slash" => KEY_SLASH = 53 / key Slash / win(0x35),
    "capslock" => KEY_CAPSLOCK = 58 / key CapsLock / win(0x3A),

    // Modifiers.
    "leftctrl" => KEY_LEFTCTRL = 29 / key LeftControl / win(0x1D),
    "rightctrl" => KEY_RIGHTCTRL = 97 / key RightControl / win_ext(0x1D),
    "leftshift" => KEY_LEFTSHIFT = 42 / key LeftShift / win(0x2A),
    "rightshift" => KEY_RIGHTSHIFT = 54 / key RightShift / win(0x36),
    "leftalt" => KEY_LEFTALT = 56 / key LeftAlt / win(0x38),
    "rightalt" => KEY_RIGHTALT = 100 / key RightAlt / win_ext(0x38),
    "leftmeta" => KEY_LEFTMETA = 125 / key LeftMeta / win_ext(0x5B),
    "rightmeta" => KEY_RIGHTMETA = 126 / key RightMeta / win_ext(0x5C),

    // Arrows.
    "up" => KEY_UP = 103 / key Up / win_ext(0x48),
    "down" => KEY_DOWN = 108 / key Down / win_ext(0x50),
    "left" => KEY_LEFT = 105 / key Left / win_ext(0x4B),
    "right" => KEY_RIGHT = 106 / key Right / win_ext(0x4D),

    // Navigation cluster.
    "insert" => KEY_INSERT = 110 / key Insert / win_ext(0x52),
    "delete" => KEY_DELETE = 111 / key Delete / win_ext(0x53),
    "home" => KEY_HOME = 102 / key Home / win_ext(0x47),
    "end" => KEY_END = 107 / key End / win_ext(0x4F),
    "pageup" => KEY_PAGEUP = 104 / key PageUp / win_ext(0x49),
    "pagedown" => KEY_PAGEDOWN = 109 / key PageDown / win_ext(0x51),

    // System keys.
    "sysrq" => KEY_SYSRQ = 99 / key SysRq / win_ext(0x37),
    "scrolllock" => KEY_SCROLLLOCK = 70 / key ScrollLock / win(0x46),
    "pause" => KEY_PAUSE = 119 / misc Pause / win_vk(0x13),
    "numlock" => KEY_NUMLOCK = 69 / key NumLock / win(0x45),

    // Keypad.
    "kp0" => KEY_KP0 = 82 / pad _0 / win(0x52),
    "kp1" => KEY_KP1 = 79 / pad _1 / win(0x4F),
    "kp2" => KEY_KP2 = 80 / pad _2 / win(0x50),
    "kp3" => KEY_KP3 = 81 / pad _3 / win(0x51),
    "kp4" => KEY_KP4 = 75 / pad _4 / win(0x4B),
    "kp5" => KEY_KP5 = 76 / pad _5 / win(0x4C),
    "kp6" => KEY_KP6 = 77 / pad _6 / win(0x4D),
    "kp7" => KEY_KP7 = 71 / pad _7 / win(0x47),
    "kp8" => KEY_KP8 = 72 / pad _8 / win(0x48),
    "kp9" => KEY_KP9 = 73 / pad _9 / win(0x49),
    "kpslash" => KEY_KPSLASH = 98 / pad Slash / win_ext(0x35),
    "kpasterisk" => KEY_KPASTERISK = 55 / pad Asterisk / win(0x37),
    "kpminus" => KEY_KPMINUS = 74 / pad Minus / win(0x4A),
    "kpplus" => KEY_KPPLUS = 78 / pad Plus / win(0x4E),
    "kpenter" => KEY_KPENTER = 96 / pad Enter / win_ext(0x1C),
    "kpdot" => KEY_KPDOT = 83 / pad Dot / win(0x53),

    // Media keys.
    "mute" => KEY_MUTE = 113 / misc Mute / win_ext(0x20),
    "volumeup" => KEY_VOLUMEUP = 115 / misc VolumeUp / win_ext(0x30),
    "volumedown" => KEY_VOLUMEDOWN = 114 / misc VolumeDown / win_ext(0x2E),
    "playpause" => KEY_PLAYPAUSE = 164 / misc PlayPause / win_ext(0x22),
    "nextsong" => KEY_NEXTSONG = 163 / misc NextSong / win_ext(0x19),
    "previoussong" => KEY_PREVIOUSSONG = 165 / misc PreviousSong / win_ext(0x10),
}

/// The evdev key code for a key, used when matching hotkey events read from
/// `/dev/input/event*`.
#[cfg(target_os = "linux")]
pub fn to_evdev(code: KeyCode) -> evdev::KeyCode {
    evdev::KeyCode(code.0)
}

/// Every friendly key name we accept, in table order.
///
/// Used by the key reference documentation and by [`suggest`].
pub fn all_names() -> &'static [&'static str] {
    NAMES
}

/// Every key code in the table, in table order.
///
/// The uinput device registers all of these as capabilities so that it looks
/// like a real keyboard to SDL and games (DESIGN.md §"`run` assembly").
pub fn all_codes() -> &'static [KeyCode] {
    CODES
}

/// The largest edit distance we will still call a typo.
const MAX_SUGGESTION_DISTANCE: usize = 2;

/// A `strsim`-ranked "did you mean ...?" suggestion for an unknown key name.
///
/// Candidates within [`MAX_SUGGESTION_DISTANCE`] edits are ranked by distance,
/// then by whether they share the misspelling's first letter (typos rarely
/// change it), then by how close their length is, and finally alphabetically so
/// the result is deterministic.
///
/// A candidate must also differ by fewer edits than the shorter of the two
/// names is long, which is what stops short nonsense from matching short keys —
/// `"zzz"` is two edits from `"z"`, but nobody meant `"z"`.
pub fn suggest(name: &str) -> Option<&'static str> {
    let name = name.trim().to_ascii_lowercase();
    if name.is_empty() {
        return None;
    }

    let first = name.chars().next();

    all_names()
        .iter()
        .copied()
        .filter_map(|candidate| {
            let distance = strsim::levenshtein(&name, candidate);
            let plausible =
                distance <= MAX_SUGGESTION_DISTANCE && distance < name.len().min(candidate.len());
            plausible.then_some((distance, candidate))
        })
        .min_by_key(|(distance, candidate)| {
            (
                *distance,
                // `false` sorts first, so a shared first letter wins ties.
                candidate.chars().next() != first,
                candidate.len().abs_diff(name.len()),
                *candidate,
            )
        })
        .map(|(_, candidate)| candidate)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    #[test]
    fn every_name_round_trips() {
        for &name in all_names() {
            let code = from_name(name).unwrap_or_else(|| panic!("'{name}' is not resolvable"));
            let back = super::name(code).unwrap_or_else(|| panic!("{code:?} has no name"));
            assert_eq!(back, name, "'{name}' did not round-trip");
            assert_eq!(
                from_name(back),
                Some(code),
                "'{name}' did not round-trip back to the same code"
            );
        }
    }

    #[test]
    fn names_and_codes_are_unique_and_aligned() {
        assert_eq!(all_names().len(), all_codes().len());

        let names: std::collections::HashSet<_> = all_names().iter().collect();
        assert_eq!(
            names.len(),
            all_names().len(),
            "duplicate key name in table"
        );

        let codes: std::collections::HashSet<_> = all_codes().iter().collect();
        assert_eq!(
            codes.len(),
            all_codes().len(),
            "duplicate key code in table"
        );

        for (&name, &code) in all_names().iter().zip(all_codes()) {
            assert_eq!(from_name(name), Some(code), "'{name}' is misaligned");
        }
    }

    /// The safety net for the literal codes in the table.
    ///
    /// The macro used to build every row out of an `evdev::KeyCode::KEY_*`
    /// constant, which made a wrong number impossible; the table now carries
    /// the number itself so that it compiles on Windows too, and this test is
    /// what replaces that guarantee. A row whose literal drifts away from the
    /// kernel's numbering fails here, naming the key.
    #[cfg(target_os = "linux")]
    #[test]
    fn every_code_matches_the_evdev_constant() {
        for &(name, code, expected) in EVDEV_ROWS {
            assert_eq!(
                code, expected.0,
                "'{name}' claims evdev code {code}, but evdev says {}",
                expected.0
            );
        }
        assert_eq!(EVDEV_ROWS.len(), all_names().len());
    }

    /// Every key we can be asked to press must be expressible to `SendInput`,
    /// or a profile using it would fail at runtime on Windows with nothing to
    /// say about which key. Compiled everywhere: the table is pure data, so
    /// Linux CI is where this gap gets caught.
    #[test]
    fn every_name_has_a_windows_encoding() {
        let missing: Vec<_> = all_names()
            .iter()
            .filter(|name| to_windows(from_name(name).unwrap()).is_none())
            .collect();
        assert!(missing.is_empty(), "no windows encoding for: {missing:?}");
    }

    /// The three shapes of the Windows column, spot-checked against the AT
    /// set-1 table: the `1..=88` identity range, the `E0` extended set, the
    /// `F13`..`F24` block, and the one virtual-key row.
    #[rstest]
    #[case("esc", WinKey::Scan(0x01))]
    #[case("a", WinKey::Scan(0x1E))]
    #[case("w", WinKey::Scan(0x11))]
    #[case("space", WinKey::Scan(0x39))]
    #[case("f1", WinKey::Scan(0x3B))]
    #[case("f12", WinKey::Scan(0x58))]
    #[case("leftctrl", WinKey::Scan(0x1D))]
    #[case("leftalt", WinKey::Scan(0x38))]
    #[case("kp1", WinKey::Scan(0x4F))]
    #[case("kpasterisk", WinKey::Scan(0x37))]
    #[case("numlock", WinKey::Scan(0x45))]
    #[case("scrolllock", WinKey::Scan(0x46))]
    #[case("f13", WinKey::Scan(0x64))]
    #[case("f24", WinKey::Scan(0x6F))]
    #[case("rightctrl", WinKey::ScanExt(0x1D))]
    #[case("rightalt", WinKey::ScanExt(0x38))]
    #[case("leftmeta", WinKey::ScanExt(0x5B))]
    #[case("rightmeta", WinKey::ScanExt(0x5C))]
    #[case("up", WinKey::ScanExt(0x48))]
    #[case("down", WinKey::ScanExt(0x50))]
    #[case("left", WinKey::ScanExt(0x4B))]
    #[case("right", WinKey::ScanExt(0x4D))]
    #[case("home", WinKey::ScanExt(0x47))]
    #[case("end", WinKey::ScanExt(0x4F))]
    #[case("pageup", WinKey::ScanExt(0x49))]
    #[case("pagedown", WinKey::ScanExt(0x51))]
    #[case("insert", WinKey::ScanExt(0x52))]
    #[case("delete", WinKey::ScanExt(0x53))]
    #[case("kpenter", WinKey::ScanExt(0x1C))]
    #[case("kpslash", WinKey::ScanExt(0x35))]
    #[case("sysrq", WinKey::ScanExt(0x37))]
    #[case("mute", WinKey::ScanExt(0x20))]
    #[case("volumedown", WinKey::ScanExt(0x2E))]
    #[case("volumeup", WinKey::ScanExt(0x30))]
    #[case("nextsong", WinKey::ScanExt(0x19))]
    #[case("playpause", WinKey::ScanExt(0x22))]
    #[case("previoussong", WinKey::ScanExt(0x10))]
    // The E1 1D 45 sequence has no single-scancode form, so this one row is
    // injected by virtual key (VK_PAUSE).
    #[case("pause", WinKey::VirtualKey(0x13))]
    fn windows_encodings_are_the_at_set_1_ones(#[case] name: &str, #[case] expected: WinKey) {
        assert_eq!(
            to_windows(from_name(name).expect("known key")),
            Some(expected)
        );
    }

    /// Everything the kernel numbers at or below 88 is its own AT set-1
    /// scancode, which is the rule the table's first column is written to.
    /// Above that, nothing may claim the identity by accident.
    #[test]
    fn the_identity_range_is_exactly_the_low_codes() {
        for &code in all_codes() {
            let win = to_windows(code).expect("every key has a windows encoding");
            if code.0 <= 88 {
                assert_eq!(
                    win,
                    WinKey::Scan(code.0),
                    "'{code}' is in the identity range but does not map to its own code"
                );
            } else {
                assert_ne!(
                    win,
                    WinKey::Scan(code.0),
                    "'{code}' is above the identity range and must not reuse its own code"
                );
            }
        }
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn every_name_has_a_uinput_event() {
        // DESIGN.md §Risks 7: verify uinput-tokio covers the whole table. Any
        // key which is not covered can still be written as a raw EV_KEY code,
        // but cannot be registered as a device capability, so a gap here is
        // worth knowing about.
        let missing: Vec<_> = all_names()
            .iter()
            .filter(|name| to_uinput(from_name(name).unwrap()).is_none())
            .collect();
        assert!(missing.is_empty(), "no uinput event for: {missing:?}");
    }

    #[cfg(target_os = "linux")]
    #[rstest]
    #[case("a", evdev::KeyCode::KEY_A)]
    #[case("z", evdev::KeyCode::KEY_Z)]
    #[case("0", evdev::KeyCode::KEY_0)]
    #[case("9", evdev::KeyCode::KEY_9)]
    #[case("f5", evdev::KeyCode::KEY_F5)]
    #[case("f24", evdev::KeyCode::KEY_F24)]
    #[case("leftctrl", evdev::KeyCode::KEY_LEFTCTRL)]
    #[case("rightmeta", evdev::KeyCode::KEY_RIGHTMETA)]
    #[case("space", evdev::KeyCode::KEY_SPACE)]
    #[case("kp1", evdev::KeyCode::KEY_KP1)]
    #[case("kpasterisk", evdev::KeyCode::KEY_KPASTERISK)]
    #[case("pause", evdev::KeyCode::KEY_PAUSE)]
    #[case("playpause", evdev::KeyCode::KEY_PLAYPAUSE)]
    #[case("previoussong", evdev::KeyCode::KEY_PREVIOUSSONG)]
    fn to_evdev_agrees_with_evdev(#[case] name: &str, #[case] expected: evdev::KeyCode) {
        let code = from_name(name).expect("known key");
        assert_eq!(to_evdev(code), expected);
        assert_eq!(code.code(), expected.0);
    }

    #[test]
    fn unknown_names_do_not_resolve() {
        assert_eq!(from_name("leftcontrol"), None);
        assert_eq!(from_name("LEFTCTRL"), None);
        assert_eq!(from_name(""), None);
        assert_eq!(name(KeyCode(60000)), None);
    }

    #[rstest]
    #[case("leftctl", "leftctrl")]
    #[case("lefctrl", "leftctrl")]
    #[case("leftctrll", "leftctrl")]
    #[case("LeftCtrl", "leftctrl")]
    #[case("esk", "esc")]
    #[case("spce", "space")]
    #[case("entre", "enter")]
    #[case("bakspace", "backspace")]
    #[case("pgup", "pageup")]
    #[case("kpplu", "kpplus")]
    #[case("volumup", "volumeup")]
    fn suggest_finds_realistic_typos(#[case] typo: &str, #[case] expected: &str) {
        assert_eq!(suggest(typo), Some(expected), "suggestion for '{typo}'");
    }

    #[rstest]
    #[case("zzz")]
    #[case("zz")]
    #[case("")]
    #[case("supercalifragilistic")]
    #[case("mouse_wheel_up")]
    fn suggest_gives_up_on_nonsense(#[case] input: &str) {
        assert_eq!(suggest(input), None, "unexpected suggestion for '{input}'");
    }

    #[test]
    fn display_names_known_keys() {
        assert_eq!(from_name("leftctrl").unwrap().to_string(), "leftctrl");
        assert_eq!(KeyCode(60000).to_string(), "<unnamed key 60000>");
    }
}
